name: 'GitHub Copilot CLI Action'
description: 'Execute GitHub Copilot CLI with a prompt and return the result'
author: 'cschleiden'

inputs:
  prompt:
    description: 'The prompt to send to GitHub Copilot CLI'
    required: true
  PAT:
    description: 'GitHub Personal Access Token for authentication'
    required: true

outputs:
  result:
    description: 'The output from the GitHub Copilot CLI command'
    value: ${{ steps.copilot-cli.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        
    - name: Install GitHub Copilot CLI
      shell: bash
      run: |
        # Install the latest version of GitHub Copilot CLI
        # Using @latest explicitly due to rapid development of this package
        npm install -g @github/copilot@latest
        
    - name: Execute Copilot CLI
      id: copilot-cli
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.PAT }}
        COPILOT_PROMPT: ${{ inputs.prompt }}
      run: |
        # Capture the output of the copilot command
        set +e  # Don't exit on error to capture both success and error cases
        output=$(copilot -p "$COPILOT_PROMPT" 2>&1)
        exit_code=$?
        set -e
        
        # Set the output for the action
        echo "result<<EOF" >> $GITHUB_OUTPUT
        echo "$output" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # If the command failed, still output the result but also show the error
        if [ $exit_code -ne 0 ]; then
          echo "::warning::Copilot CLI command exited with code $exit_code"
        fi
        
        # Always exit successfully so the action doesn't fail if copilot has issues
        exit 0