name: Test Copilot CLI Action

on:
  workflow_dispatch:
    inputs:
      test_prompt:
        description: 'Test prompt for Copilot CLI'
        required: true
        default: 'Write a hello world function in JavaScript'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Copilot CLI Action
        uses: ./
        with:
          prompt: ${{ github.event.inputs.test_prompt || 'Write a hello world function in JavaScript' }}
          PAT: ${{ secrets.GITHUB_TOKEN }}
        id: copilot-test
        
      - name: Display Result
        run: |
          echo "Copilot CLI Result:"
          echo "${{ steps.copilot-test.outputs.result }}"